# This workflow will upload a Python Package using Twine when a release is created
# The CI build wheel package is used to build python wheels on multiple environments
# Based on example: https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml


name: Build and upload to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build pure python wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install wheel
        run: pip install wheel

      - name: Build wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    # To publish when a GitHub Release is created, use the following rule:
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}